"""
End-to-end RAG pipeline: user question -> retrieval -> prompt -> EduVerse-1 generation.

Includes --extractive mode: builds answers directly from retrieved context,
no neural generation involved. Use this while EduVerse-1's generation
quality is still limited by corpus size.
"""

from __future__ import annotations

from dataclasses import dataclass

from .retrieve import Retriever, RetrievedChunk


PROMPT_TEMPLATE = """Context: {context}

Question: {question}

Answer:"""


def build_prompt(chunks: list[RetrievedChunk], question: str) -> str:
    context = " ".join(c.text for c in chunks)
    return PROMPT_TEMPLATE.format(context=context, question=question)


@dataclass
class RAGResult:
    question: str
    prompt: str
    retrieved_chunks: list[RetrievedChunk]
    answer: str


class RAGPipeline:
    def __init__(self, retriever: Retriever, generate_fn, k: int = 3, max_context_words: int = 200):
        self.retriever = retriever
        self.generate_fn = generate_fn
        self.k = k
        self.max_context_words = max_context_words

    def _trim_to_budget(self, chunks: list[RetrievedChunk]) -> list[RetrievedChunk]:
        kept = []
        total_words = 0
        for c in chunks:
            wc = len(c.text.split())
            if total_words + wc > self.max_context_words:
                if kept:
                    break
            kept.append(c)
            total_words += wc
        return kept

    def answer(self, question: str) -> RAGResult:
        raw_chunks = self.retriever.retrieve(question, k=self.k)
        chunks = self._trim_to_budget(raw_chunks)
        prompt = build_prompt(chunks, question)
        answer = self.generate_fn(prompt)
        return RAGResult(question=question, prompt=prompt, retrieved_chunks=chunks, answer=answer)


def echo_stub_generator(prompt: str) -> str:
    return (
        "[EduVerse-1 not yet loaded — this is a stub response "
        "echoing the prompt. Pass --checkpoint/--tokenizer to fix this]\n"
        + prompt
    )


if __name__ == "__main__":

    import argparse

    parser = argparse.ArgumentParser(description="Run the full Sanjivani RAG pipeline")
    parser.add_argument("--index", default="data/sanjivani.index")
    parser.add_argument("--meta", default="data/sanjivani_meta.jsonl")
    parser.add_argument("--query", required=True)
    parser.add_argument("--k", type=int, default=3)
    parser.add_argument("--checkpoint", default=None,
        help="Path to a trained EduVerse-1 checkpoint.pt. If omitted, falls back to the echo stub.")
    parser.add_argument("--tokenizer", default=None,
        help="Path to the trained tokenizer .json. Required if --checkpoint is set.")
    parser.add_argument("--max_new_tokens", type=int, default=80)
    parser.add_argument("--extractive", action="store_true",
        help="Skip the neural generator entirely and build the answer directly from retrieved context.")

    args = parser.parse_args()

    retriever = Retriever(args.index, args.meta)

    if args.extractive:
        from src.model_free.extractive_generator import extractive_answer

        print("Running in EXTRACTIVE mode — answers are built directly from "
              "retrieved text, not generated by EduVerse-1.")

        raw_chunks = retriever.retrieve(args.query, k=args.k)
        answer_text = extractive_answer(raw_chunks)

        print("\n" + "=" * 70)
        print("RETRIEVED CONTEXT")
        print("=" * 70)
        for c in raw_chunks:
            print(f"  [{c.score:.3f}] {c.source_file}: {c.text[:150]}...")

        print("\n" + "=" * 70)
        print("ANSWER (extractive mode)")
        print("=" * 70)
        print(answer_text)

        raise SystemExit(0)

    if args.checkpoint:
        if not args.tokenizer:
            parser.error("--tokenizer is required when --checkpoint is set")

        import sys
        from pathlib import Path
        sys.path.insert(0, str(Path(__file__).parent.parent / "model"))
        from generate import EduVerseGenerator

        print(f"Loading EduVerse-1 from {args.checkpoint} ...")
        generator = EduVerseGenerator(args.checkpoint, args.tokenizer)

        def generate_fn(prompt: str) -> str:
            return generator(prompt, max_new_tokens=args.max_new_tokens)
    else:
        print("WARNING: no --checkpoint given, using the echo stub. You will NOT get a real answer.")
        generate_fn = echo_stub_generator

    pipeline = RAGPipeline(retriever, generate_fn=generate_fn, k=args.k)
    result = pipeline.answer(args.query)

    print("\n" + "=" * 70)
    print("RETRIEVED CONTEXT")
    print("=" * 70)
    for c in result.retrieved_chunks:
        print(f"  [{c.score:.3f}] {c.source_file}: {c.text[:150]}...")

    print("\n" + "=" * 70)
    print("ANSWER")
    print("=" * 70)
    print(result.answer)